name: edspert
description: "A new Flutter project."


publish_to: "none" 













version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"







dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  
  
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  firebase_core: ^2.31.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.5
  bloc: ^8.1.4
  hl_image_picker: ^1.2.14
  firebase_storage: ^11.7.5
  image_picker: ^1.1.1
  cloud_firestore: ^4.17.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0





flutter:
  
  
  
  uses-material-design: true

  
  assets:
    - images/
    

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
