// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO5sHaVxYsTO-4DAqKmUeLRzqV_aKRDPc',
    appId: '1:78344918001:android:6806a3fdc94d3fbcb92a50',
    messagingSenderId: '78344918001',
    projectId: 'edspert-flutter',
    storageBucket: 'edspert-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX8Im9KiWkZQW-Egxp683PcyMKzCebn_o',
    appId: '1:78344918001:ios:7e2394b6682c4e3cb92a50',
    messagingSenderId: '78344918001',
    projectId: 'edspert-flutter',
    storageBucket: 'edspert-flutter.appspot.com',
    androidClientId: '78344918001-7t0qv1h718ja4lep2f3ip29geem2s004.apps.googleusercontent.com',
    iosClientId: '78344918001-345tk7hic9o05gqujs86h976mgmdaij1.apps.googleusercontent.com',
    iosBundleId: 'com.example.edspert',
  );
}
